# Generated by Django 4.2.4 on 2023-08-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('row', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(default=0, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='movie',
            name='sbor',
            field=models.PositiveIntegerField(default=0, verbose_name='Сборы'),
        ),
    ]
