# Generated by Django 4.2.4 on 2023-08-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('row', '0002_movie_budget_movie_sbor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='', max_length=50, verbose_name='Страна'),
        ),
    ]
